# Generated by Django 6.0.3 on 2026-03-14 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_customer_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_customer_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('customer_count_with_dues', models.IntegerField(default=0)),
                ('total_supplier_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_supplier_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('supplier_count_with_dues', models.IntegerField(default=0)),
                ('net_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dues Summaries',
                'db_table': 'dues_summary',
            },
        ),
        migrations.CreateModel(
            name='CustomerDue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('current', 'Current'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('written_off', 'Written Off')], default='current', max_length=20)),
                ('days_overdue', models.IntegerField(default=0)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_sent', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_dues', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='customers.customer')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due', to='sales.salesorder')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customer_dues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_dues',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_number', models.CharField(max_length=50, unique=True)),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('upi', 'UPI')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_generated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer_due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='dues.customerdue')),
            ],
            options={
                'db_table': 'payment_collections',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('current', 'Current'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='current', max_length=20)),
                ('days_overdue', models.IntegerField(default=0)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_sent', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_dues', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due', to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_dues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier_dues',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDisbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disbursement_number', models.CharField(max_length=50, unique=True)),
                ('disbursement_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online Payment')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disbursed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier_due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='dues.supplierdue')),
            ],
            options={
                'db_table': 'payment_disbursements',
                'ordering': ['-disbursement_date'],
            },
        ),
        migrations.CreateModel(
            name='DueReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone Call')], max_length=20)),
                ('reminder_date', models.DateField(auto_now_add=True)),
                ('scheduled_date', models.DateField()),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_received', models.BooleanField(default=False)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='dues.customerdue')),
                ('supplier_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='dues.supplierdue')),
            ],
            options={
                'db_table': 'due_reminders',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('write_off_number', models.CharField(max_length=50, unique=True)),
                ('write_off_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('bankrupt', 'Customer Bankrupt'), ('unreachable', 'Customer Unreachable'), ('disputed', 'Disputed Amount'), ('time_barred', 'Time Barred'), ('other', 'Other')], max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_write_offs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_write_offs', to=settings.AUTH_USER_MODEL)),
                ('customer_due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='dues.customerdue')),
            ],
            options={
                'db_table': 'write_offs',
            },
        ),
        migrations.AddIndex(
            model_name='customerdue',
            index=models.Index(fields=['status'], name='customer_du_status_9daed5_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdue',
            index=models.Index(fields=['due_date'], name='customer_du_due_dat_d46f84_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdue',
            index=models.Index(fields=['customer', 'status'], name='customer_du_custome_5c04ed_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdue',
            index=models.Index(fields=['status'], name='supplier_du_status_626d62_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdue',
            index=models.Index(fields=['due_date'], name='supplier_du_due_dat_fd1ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdue',
            index=models.Index(fields=['supplier', 'status'], name='supplier_du_supplie_034027_idx'),
        ),
    ]
